version: '3.4'
services:
  influxdb:
    container_name: influxdb
    image: influxdb
    ports:
      - 8886:8086
    volumes:
      - influxdb-data:/var/lib/influxdb
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${INFLUXDB_HOST}
      - VIRTUAL_PORT=8086
      - LETSENCRYPT_HOST=${INFLUXDB_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
      - INFLUXDB_READ_USER=${INFLUXDB_READ_USER}
      - INFLUXDB_READ_USER_PASSWORD=${INFLUXDB_READ_USER_PASSWORD}
      - INFLUXDB_WRITE_USER=${INFLUXDB_WRITE_USER}
      - INFLUXDB_WRITE_USER_PASSWORD=${INFLUXDB_WRITE_USER_PASSWORD}
      - INFLUXDB_REPORTING_DISABLED=true
    restart: always
      default:
        aliases:
         - ${CONTAINER_NAMESPACE}influxdb
      nginx_proxy:

  telegraf:
    container_name: telegraf
    image: telegraf
    hostname: telegraf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    depends_on:
      - influxdb
    networks:
      - default
    command: -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d    
    
  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "0"
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${CHRONOGRAF_HOST}
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=${CHRONOGRAF_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - INFLUXDB_URL=http://${CONTAINER_NAMESPACE}influxdb:8886
      - INFLUXDB_USERNAME=${INFLUXDB_READ_USER}
      - INFLUXDB_PASSWORD=${INFLUXDB_READ_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
    links:
      - influxdb
    restart: always

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    user: "0"
    volumes:
      - mqtt-data:/mosquitto/data
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${MQTT_HOST}
      - VIRTUAL_PORT=1883
      - LETSENCRYPT_HOST=${MQTT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    restart: always

volumes:
  influxdb-data:
    driver: local
    name: influxdb-data
  grafana-data:
    driver: local
    name: grafana-data
  mqtt-data:
    driver: local
    name: mqtt-data